name: Test/Lint/Fmt/Vet
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1
    steps:
      - uses: actions/checkout@v4

      - name: Get latest chikvdf libs
        run: |
          apt-get update && apt-get install -y unzip
          LATEST_CHIKVDF=$(curl -Ls "https://api.github.com/repos/Chik-Network/chikvdf/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "Latest chikvdf is: $LATEST_CHIKVDF"
          mkdir chikvdfc
          cd chikvdfc || exit 1
          wget https://github.com/Chik-Network/chikvdf/releases/download/$LATEST_CHIKVDF/chikvdfc-ubuntu-intel.zip
          unzip chikvdfc-ubuntu-intel.zip
          echo "CGO_CFLAGS=-I${GITHUB_WORKSPACE}/chikvdfc/chikvdfc-ubuntu-intel" >> "$GITHUB_ENV"

      - name: Test
        run: make test
